project:
  type: website
  output-dir: docs

extensions:
  - _extensions/apaquarto

format:
  html:
    theme: 
      - theme/d2mr-theme.scss
    toc: true

website:
  title: "Schelling Games"
  navbar:
    background: primary
    search: false
    left:
      - text: Play the Game
        href: https://forms.gle/RB2eq8sySoBwVsqF7
      - text: About
        href: index.html
      - text: All Responses
        href: all-responses.html
      - text: MA Responses
        href: ma-responses.html
      - text: Recent Responses
        href: recent-responses.html
