project:
    type: website

format:
    html:
        theme: 
          - theme/d2mr-theme.scss
        toc: true

website:
    title: "Schelling Games"
    navbar:
        left:
            - text: Play the Game
              href: https://forms.gle/RB2eq8sySoBwVsqF7
            - text: About
              href: index.qmd
            - text: All Responses
              href: all-responses.qmd
            - text: MA Responses
              href: ma-responses.qmd
            - text: Recent Responses
              href: recent-responses.qmd